  #Install redis-server for Debian systems

#Install Debian dependancy
- name: 'install dependancy'
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - build-essential
    - tcl

#Install tcl dependancy
- name: 'Install redis-server'
  apt:
    name: redis-server
    state: latest

#Start redis in Debian systems
- name: "start redis"
  service:
    name: redis-server
    state: started
    enabled: yes

#Check redis is well installed
- name: "Test redis is well installed"
  command: redis-cli ping
  register: redis_test_output
  failed_when: "'PONG' not in redis_test_output.stdout"

#configure redis to be connected from outside
- name: "Configuring the redis"
  template:
    src: ../templates/redis.conf.j2
    dest: /etc/redis.conf
    owner: vagrant
    mode: 0644

- name: restart redis server
  service:
    name: redis-server
    state: restarted
 
